name: ezWGD-AutoCI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # step1 code quality check
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python environment.
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies.
        run: |
          pip install uv
          uv pip install --system -e .
          uv pip install --system ruff pytest pytest-cov uv-build mkdocs mkdocs-material mkdocstrings[python] mkdocs-static-i18n

      - name: Script linting check.
        run: |
          ruff check .

      - name: Auto testing.
        run: |
          pytest

      - name: Auto generate documents.
        run: |
          mkdocs build

      - name: Upload coverage result to codecov.
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
